### PR TITLE
Cast support for time

### LINKED ISSUE #399: Build fails for `DATE '9000-02-29'`
In one of the local builds, the randomly generated `date` `9000-02-29` caused an error failing with an exception `org.partiql.lang.syntax.ParserException: Text '9000-02-29' could not be parsed: Invalid date 'February 29' as '9000' is not a leap year`
Apparently, `9000` is not a leap year indeed. 
Fix the random `DATE` string [generator](https://github.com/partiql/partiql-lang-kotlin/blob/eee99ae37bd60fd92ac6ae3d8cf0558aef61223f/lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt#L177) to handle such cases.

### PR DESCRIPTION
**Pull request by abhikuhikar**
*Issue #, if available:*

*Description of changes:*
- Resolves #399 (very minor change to fix the failing local build)
- Extends `CAST` to support all the variants of `TIME` type.

*Behavior for CAST to TIME type:*
 -  `Precision` is inferred from the values in case the `precision` is not explicitly specified.
 - `Timestamps` with undefined (or `null`) `timezone` _cannot_ be cast to `TIME WITH TIME ZONE`.
 - Invalid text (time string of invalid format) fails when cast to `TIME` or `TIME WITH TIME ZONE`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 1]
```diff
@@ -320,10 +329,89 @@ fun ExprValue.cast(
...
+                                null
+                            }
+                            return valueFactory.newTime(Time.of(time.localTime.hour, time.localTime.minute, time.localTime.second, time.localTime.nano, precision, tzMinutes))
+                        }
+                        type == TIMESTAMP -> {
+                            val ts = timestampValue()
+                            val precision = when {
+                                precisionProvided > MAX_PRECISION_FOR_TIME -> ts.decimalSecond.scale()
+                                else -> precisionProvided
+                            }
```
Comment (almann) [inline lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:355]: Again, `precisionProvided` (i.e. the static constraint) should not _ever_ be more than `MAX_PRECISION_FOR_TIME`.  If it is, that is an error.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 2]
```diff
@@ -320,10 +329,89 @@ fun ExprValue.cast(
...
+                                precision,
+                                if (timezone == 1) {
+                                    ts.localOffset?: castFailedErr(
+                                        "Can't convert timestamp value with undefined time zone to TIME WITH TIME ZONE.",
+                                        internal = false
+                                    )
+                                } else {
+                                    null
+                                }
+                            )
```
Comment (almann) [inline lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:370]: You should really push this logic into `Time`.  Maybe somthing like `Time.from(Timestamp)`.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 3]
```diff
@@ -320,10 +329,89 @@ fun ExprValue.cast(
...
+                            return valueFactory.newTime(Time.of(time.localTime.hour, time.localTime.minute, time.localTime.second, time.localTime.nano, precision, tzMinutes))
+                        }
+                        type == TIMESTAMP -> {
+                            val ts = timestampValue()
+                            val precision = when {
+                                precisionProvided > MAX_PRECISION_FOR_TIME -> ts.decimalSecond.scale()
+                                else -> precisionProvided
+                            }
+                            return valueFactory.newTime(
+                                ts.hour,
```
Comment (almann) [inline lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:357]: I think this is handled in a dependent PR, but really should just be using `Time.of`.

File: lang/src/org/partiql/lang/eval/time/TimeExtensions.kt [hunk 4]
```diff
@@ -2,14 +2,56 @@ package org.partiql.lang.util
...
 /**
  * Returns the string representation of the [ZoneOffset] in HH:mm format.
  */
 internal fun ZoneOffset.getOffsetHHmm(): String =
     (if(totalSeconds >= 0) "+" else "-") +
-    (totalSeconds / SECONDS_PER_HOUR).absoluteValue.toString().padStart(2, '0') +
+    hour.absoluteValue.toString().padStart(2, '0') +
     ":" +
-    ((totalSeconds / SECONDS_PER_MINUTE) % SECONDS_PER_MINUTE).absoluteValue.toString().padStart(2, '0')
+    minute.absoluteValue.toString().padStart(2, '0')
```
Comment (almann) [inline lang/src/org/partiql/lang/eval/time/TimeExtensions.kt:29]: Much nicer!

File: lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt [hunk 5]
```diff
@@ -8,14 +8,12 @@ import org.partiql.lang.domains.id
 import java.util.*
 import org.partiql.lang.errors.ErrorCode
 import org.partiql.lang.errors.Property
-import org.partiql.lang.util.softAssert
+import org.partiql.lang.util.LOCAL_TIMEZONE_OFFSET
```
Comment (almann) [inline lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt:11]: I might have missed this, but what is it--is it a statically defined local timezone offset based on JVM settings?

**Review by almann — CHANGES_REQUESTED** [review]

File: lang/resources/org/partiql/type-domains/partiql.ion [hunk 6]
```diff
@@ -361,7 +361,13 @@
             (blob_type)
             (clob_type)
             (date_type)
-            (time_type)
+
+            // TIME : timezoneSpecified is 1 if time zone is specified else 0
+            //        precision is defaulted to the length of the mantissa of the second's value if the precision is not specified.
+            // Note: This logic is implemented in SqlParser.
+            // TODO: Change timezoneSpecified to boolean or ionBool.
+            (time_type timezoneSpecified::(? int) precision::(? int))
```
[the remark this answers is not in the document]
Comment (dlurton) [reply lang/resources/org/partiql/type-domains/partiql.ion:369]: use `ion` type here, actually.

[the remark this answers is not in the document]
Comment (abhikuhikar) [reply lang/resources/org/partiql/type-domains/partiql.ion:369]: Added explicit types to handle this.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 7]
```diff
@@ -239,7 +248,7 @@ fun ExprValue.cast(
     when {
         type.isUnknown && targetType == ExprValueType.MISSING -> return valueFactory.missingValue
         type.isUnknown && targetType == ExprValueType.NULL -> return valueFactory.nullValue
-        type.isUnknown || type == targetType -> return this
+        type.isUnknown || (type == targetType && type != TIME) -> return this
```
[the remark this answers is not in the document]
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:251]: Sure. I have added a comment here. I am conditioning on `SqlDataType` as we discussed in the meeting the other day. This is not great (as `StaticType`) but far better than the run-time type `ExprValueType`.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 8]
```diff
@@ -191,14 +198,16 @@ private val datePatternRegex = Regex("\\d\\d\\d\\d-\\d\\d-\\d\\d")
  * [ExprValueType.isNumber], and *LOB types* is defined by [ExprValueType.isLob]
  *
  * @param ion The ion system to synthesize values with.
- * @param targetType The target type to cast this value to.
+ * @param targetDataType The target type to cast this value to.
```
[the remark this answers is not in the document]
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:201]: Updated the kdoc.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 9]
```diff
@@ -320,10 +329,89 @@ fun ExprValue.cast(
...
+
+                            // Check if precision is specified or not. Value greater than MAX_PRECISION_FOR_TIME indicates that the precision was not specified
+                            // In this case infer the precision from the TIME string.
+                            val precision = when {
+                                precisionProvided > MAX_PRECISION_FOR_TIME -> getPrecisionFromTimeString(stringValue())
+                                else -> precisionProvided
+                            }
+                            return valueFactory.newTime(Time.of(localTime.hour, localTime.minute, localTime.second, localTime.nano, precision,
+                                zoneOffset?.totalSeconds?.div(SECONDS_PER_MINUTE)
+                            ))
```
[the remark this answers is not in the document]
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:401]: You are right. This can be refactored. I will refactor this once I merge master into this branch.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 10]
```diff
@@ -320,10 +329,89 @@ fun ExprValue.cast(
...
                 }
+                TIME -> {
+                    val (timezone, precisionProvided) = targetDataType.args.map { it.toInt() }
+                    when {
+                        // Even though the target type is TIME, the value may differ depending on timezone and precision provided.
+                        type == TIME -> {
+                            val time = timeValue()
+                            val precision = when {
+                                // precisionProvided > MAX_PRECISION_FOR_TIME indicates that the precision was not specified.
+                                precisionProvided > MAX_PRECISION_FOR_TIME -> time.precision
```
[the remark this answers is not in the document]
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:340]: Added explicit types to handle this. This logic no longer exists.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 11]
```diff
@@ -320,10 +329,89 @@ fun ExprValue.cast(
...
+                                else -> precisionProvided
+                            }
+                            val tzMinutes = if (timezone == 1) {
+                                time.zoneOffset?.totalSeconds?.div(SECONDS_PER_MINUTE) ?: LOCAL_TIMEZONE_OFFSET.totalSeconds / SECONDS_PER_MINUTE
+                            } else {
```
[the remark this answers is not in the document]
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:345]: Sure. Will move it to `Time`

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt (hunk 1 above)
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:355]: This logic no longer exists.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt (hunk 2 above)
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:370]: Sure. Will move it to `Time`

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 12]
```diff
@@ -320,10 +329,89 @@ fun ExprValue.cast(
...
+                            return valueFactory.newTime(
+                                ts.hour,
+                                ts.minute,
+                                ts.second,
+                                (ts.decimalSecond.remainder(BigDecimal.ONE) * NANOS_PER_SECOND).toInt(),
+                                precision,
+                                if (timezone == 1) {
+                                    ts.localOffset?: castFailedErr(
+                                        "Can't convert timestamp value with undefined time zone to TIME WITH TIME ZONE.",
+                                        internal = false
```
[the remark this answers is not in the document]
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:365]: Sure. Removed this.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt (hunk 3 above)
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:357]: This logic no longer exists.

File: lang/src/org/partiql/lang/eval/time/TimeExtensions.kt (hunk 4 above)
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/time/TimeExtensions.kt:29]: Thanks.

File: lang/src/org/partiql/lang/eval/time/TimeExtensions.kt [hunk 13]
```diff
@@ -2,14 +2,56 @@ package org.partiql.lang.util
...
+    get() = totalSeconds / SECONDS_PER_HOUR
+
+/**
+ * Get time zone offset minute
+ */
+internal val ZoneOffset.minute : Int
+    get() = (totalSeconds / SECONDS_PER_MINUTE) % SECONDS_PER_MINUTE
+
+/**
+ * Gets the precision from the time string of the format 'HH:MM:SS[.ddd....][+|-HH:MM]'.
```
[the remark this answers is not in the document]
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/time/TimeExtensions.kt:44]: Changed. Thanks.

File: lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt (hunk 5 above)
Comment (abhikuhikar) [reply lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt:11]: It is, yes. But this will be changed to `+00:00` as discussed in a separate PR.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt (hunk 2 above)
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:370]: On second look, it is difficult to push the entire logic into `Time` as we still need to check if the `targetDataType` is `TIME` or `TIME WITH TIME ZONE`.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt (hunk 9 above)
[the remark this answers is not in the document]
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt:401]: I will cut an issue to make this refactor. Punting it for now.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 14]
```diff
@@ -329,43 +345,38 @@ fun ExprValue.cast(
...
                                 (ts.decimalSecond.remainder(BigDecimal.ONE) * NANOS_PER_SECOND).toInt(),
-                                precision,
-                                if (timezone == 1) {
-                                    ts.localOffset?: castFailedErr(
+                                precision?: ts.decimalSecond.scale(),
+                                when (targetSqlDataType) {
+                                    SqlDataType.TIME_WITH_TIME_ZONE -> ts.localOffset?: castFailedErr(
                                         "Can't convert timestamp value with undefined time zone to TIME WITH TIME ZONE.",
                                         internal = false
                                     )
```
Comment (almann) [inline lang/src/org/partiql/lang/eval/ExprValueExtensions.kt]: Isn't this case `-00:00`, is that not supported?  If not, we should put a more meaningful error message.

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt [hunk 15]
```diff
@@ -384,20 +395,19 @@ fun ExprValue.cast(
...
+                                Time.of(
+                                    localTime.hour,
+                                    localTime.minute,
+                                    localTime.second,
+                                    localTime.nano,
+                                    precision?: getPrecisionFromTimeString(stringValue()),
+                                    when (targetSqlDataType) {
+                                        SqlDataType.TIME_WITH_TIME_ZONE -> zoneOffset.totalSeconds / SECONDS_PER_MINUTE
+                                        else -> null
+                                    }
```
Comment (almann) [inline lang/src/org/partiql/lang/eval/ExprValueExtensions.kt]: I would extract this as a variable--it is confusing to nest it here.

File: lang/src/org/partiql/lang/eval/ExprValueType.kt [hunk 16]
```diff
@@ -174,30 +174,31 @@ enum class ExprValueType(val typeNames: List<String>,
...
+                SqlDataType.CLOB               -> ExprValueType.CLOB
+                SqlDataType.BLOB               -> ExprValueType.BLOB
+                SqlDataType.STRUCT             -> ExprValueType.STRUCT
+                SqlDataType.TUPLE              -> ExprValueType.STRUCT
+                SqlDataType.LIST               -> ExprValueType.LIST
+                SqlDataType.SEXP               -> ExprValueType.SEXP
+                SqlDataType.BAG                -> ExprValueType.BAG
+                SqlDataType.DATE               -> ExprValueType.DATE
+                SqlDataType.TIME,
+                SqlDataType.TIME_WITH_TIME_ZONE -> ExprValueType.TIME
```
Comment (almann) [inline lang/src/org/partiql/lang/eval/ExprValueType.kt:201]: What is going on here with the whitespace changes?

File: lang/src/org/partiql/lang/syntax/SqlParser.kt [hunk 17]
```diff
@@ -1415,10 +1374,28 @@ class SqlParser(private val ion: IonSystem) : Parser {
 
             else -> ParseNode(TYPE, head, emptyList(), tail)
         }
-        // Check for the optional time zone for TIME
+        // Check for the optional "WITH TIME ZONE" specifier for TIME and validate the value of precision.
+        // Note that this needs to be checked explicitly as the keywordtext for "TIME WITH TIME ZONE" consists of multiple words.
```
Comment (almann) [inline lang/src/org/partiql/lang/syntax/SqlParser.kt:1383]: Do you think this should be in the lexer?  Or rather, did we sort that out in another PR?

**Review by almann — COMMENTED** [review]
I think this is really close, some questions/minor stuff below and I think I am ready to :ship:

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt (hunk 14 above)
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt]: I see. I will change the error message. [This](https://www.javadoc.io/doc/com.amazon.ion/ion-java/latest/com/amazon/ion/Timestamp.html#getLocalOffset--) is the documentation for the `getLocalOffset` of `ion Timestamp`.
Would this error message work - 
```
"Can't convert timestamp value with unknown local offset to TIME WITH TIME ZONE.",
```

File: lang/src/org/partiql/lang/syntax/SqlParser.kt (hunk 17 above)
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/syntax/SqlParser.kt:1383]: We discussed about having a keyword associated with `TIME WITH TIME ZONE` in the lexer. That is doable. However, I don't think we can model `TIME (<precision>) WITH TIME ZONE` in the lexer DFA.
Another option was to model just `WITH TIME ZONE` in the lexer but note that `WITH TIME ZONE` on itself shouldn't be considered as a keyword (or a series of keywords).
Considering all these, I thought it wasn't possible to model this in lexer DFA.

File: lang/src/org/partiql/lang/eval/ExprValueType.kt (hunk 16 above)
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueType.kt:201]: I was trying to align RHS on one column considering how it was before. Looking at it now, I don't seem to have done a thorough job (as it is still not aligned as I intended). 😄 
Should I remove the whitespace change?

File: lang/src/org/partiql/lang/eval/ExprValueExtensions.kt (hunk 15 above)
Comment (abhikuhikar) [reply lang/src/org/partiql/lang/eval/ExprValueExtensions.kt]: I see. Changed it.

**Review by almann — APPROVED** [review]
:ship:
