### PR TITLE
Removes double-pass to increase parsing performance, and adds interruption/exception handling

### LINKED ISSUE #747: Remove double-pass for tokenizing queries
Probably a good idea to discuss 'why' this is needed.

I.e., the visitor visits the params in 2-dimensional tree traversal order, but the ordinal of the parameters is implicit in the 1-dimensional traversal of the token stream.

It might also be possibly to "wrap" the `GeneratedLexer` in your own `TokenSource`-derivative that delegates to to all other methods, but "wraps" `nextToken` to count tokens as they are emitted by the Lexer. The downside is more complicated lifetime of shared objects, but it would only require a single lexer pass through the input.

_Originally posted by @jpschorr in https://github.com/partiql/partiql-lang-kotlin/pull/711#discussion_r962060141_

### PR DESCRIPTION
**Pull request by johnedquinn**
## Relevant Issues
- Related To #710, #895
- Resolves #747 

## Description
- Removes double-pass to increase parsing performance
- Adds interruption handling to both parse methods (LL and SLL)
  - We discussed the importance of allowing our customers to fail quickly -- but that's out of the scope of a patch release.
  - With these changes, we want to make our parser faster -- while also ensuring they can always interrupt the parse at any point if they desire. We also include interruption handling for creating the token stream.
- Adds more exception handling
  -  With this, we'd like to make sure that our public APIs are always throwing the correct exceptions, so for `parseAstStatement`, we catch all to make sure our public API is never broken.

## Benchmarking Analysis
- With local benchmarking, the recent changes in the PartiQLParser have reduced the added time between parsing using SqlParser and PartiQLParser to ~28%.
- With these changes, the same tests have seen the added time at ~15%.

## Benchmarking Results

Raw benchmark results for 10 iterations, 2 forks, 5 warm-ups for 31 tests ranging in length/features/complexity.
| Test    | SqlParser   | PartiQLParser | Time Difference |
|---------|-------------|---------------|-----------------|
| 0       | 6.495       | 9.96          | 53%             |
| 1       | 28.623      | 58.405        | 104%            |
| 2       | 14.366      | 16.683        | 16%             |
| 3       | 53.845      | 57.578        | 7%              |
| 4       | 24.938      | 28.558        | 15%             |
| 5       | 84.142      | 82.802        | -2%             |
| 6       | 10.746      | 14.402        | 34%             |
| 7       | 33.772      | 44.056        | 30%             |
| 8       | 28.438      | 66.866        | 135%            |
| 9       | 47.667      | 99.428        | 109%            |
| 10      | 56.663      | 70.928        | 25%             |
| 11      | 45.946      | 64.939        | 41%             |
| 12      | 192.699     | 137.09        | -29%            |
| 13      | 45.598      | 45.772        | 0%              |
| 14      | 132.207     | 109.9         | -17%            |
| 15      | 36.994      | 37.646        | 2%              |
| 16      | 8.919       | 5.692         | -36%            |
| 17      | 18.075      | 20.713        | 15%             |
| 18      | 21.69       | 17.351        | -20%            |
| 19      | 163.964     | 170.27        | 4%              |
| 20      | 60.289      | 51.006        | -15%            |
| 21      | 32.053      | 30.716        | -4%             |
| 22      | 27.125      | 29.417        | 8%              |
| 23      | 46.31       | 53.164        | 15%             |
| 24      | 86.379      | 99.729        | 15%             |
| 25      | 87.048      | 75.623        | -13%            |
| 26      | 174.253     | 202.104       | 16%             |
| 27      | 103.761     | 86.619        | -17%            |
| 28      | 165.024     | 148.118       | -10%            |
| 29      | 474.43      | 355.534       | -25%            |
| 30      | 1132.715    | 1180.907      | 4%              |
| AVERAGE | 111.1346452 | 111.9992258   | 15%             |

## Other Information
- Updated Unreleased Section in CHANGELOG: **NO**
  - Not yet
- Any backward-incompatible changes? **NO**
- Any new external dependencies? **NO**

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: lang/src/org/partiql/lang/syntax/PartiQLParser.kt [hunk 1]
```diff
@@ -184,4 +190,33 @@ internal class PartiQLParser(
...
+     */
+    internal class InterruptibleParser(input: TokenStream) : GeneratedParser(input) {
+        override fun enterRule(localctx: ParserRuleContext?, state: Int, ruleIndex: Int) {
+            checkThreadInterrupted()
+            super.enterRule(localctx, state, ruleIndex)
+        }
+    }
+
+    /**
+     * This token stream creates [parameterIndexes], which is a map with key-value pairs, where the keys represent the
```
Comment (alancai98) [inline lang/src/org/partiql/lang/syntax/PartiQLParser.kt:205]: nit: redundant description

```suggestion
     * This token stream creates [parameterIndexes], which is a map, where the keys represent the
```

File: lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt [hunk 2]
```diff
@@ -3,6 +3,12 @@ package org.partiql.lang.thread
```
Comment (alancai98) [inline lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt:3]: Think we also need to:
1. Update CHANGELOG.md w/ these changes
2. Update PR description with more concrete benchmarking results
3. Include why interruption and exception handling was added -- I know there was some offline discussion but would be good to capture it in the PR

**Review by alancai98 — COMMENTED** [review]
Looks good overall. Had some minor nits and some other updates I think are needed to document the changes and performance improvements.

File: lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt (hunk 2 above)
Comment (johnedquinn) [reply lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt]: Done. LMK if that works.

**Review by alancai98 — APPROVED** [review]

File: lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt (hunk 2 above)
Comment (alancai98) [reply lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt]: Thanks, changes look good
