### PR TITLE
Fix `LIMIT` clause execution order

### LINKED ISSUE #281: Incorrect execution order for `LIMIT` clause during query execution
Currently, the execution order is:

- `FROM`
- `WHERE`
- `LIMIT`
- `GROUP BY` (if present)
- `HAVING` (if present)
- ...`SELECT`-list or `SELECT VALUE` projection..

In reality it should probably be one of two options:

- `FROM`
- `WHERE`
- `GROUP BY` (if present)
- `HAVING` (if present)
- `LIMIT` (option 1)
- ...`SELECT`-list or `SELECT VALUE` projection..
- `LIMIT` (option 2)

The impact of this bug can be seen when it's used with `GROUP BY`:

```
PartiQL> select * from `[{foo: 1, bar: 10}, {foo: 1, bar: 11}]` AS f GROUP BY f.foo GROUP AS g LIMIT 1
   | ===' 
<<
  {
    'foo': 1,
    'g': <<
      {
        'f': {
          'foo': 1,
          'bar': 10
        }
      }
    >>
  }
>>
```

`LIMIT` should applied *after* the group has occurred and not before.  Since this query is has only one group, the result should be unaffected by `LIMIT 1`.   The expected result is:

```
<<
  {
    'foo': 1,
    'g': <<
      {
        'f': {
          'foo': 1,
          'bar': 10
        }
      },
      {
        'f': {
          'foo': 1,
          'bar': 11
        }
      }
    >>
  }
>>
```

### PR DESCRIPTION
**Pull request by alancai98**
Fixes #281

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt [hunk 1]
```diff
@@ -889,6 +889,49 @@ internal class EvaluatingCompiler(
         }
     }
 
+    private fun compileLimit(limitClause: ExprNode, env: Environment) : Long {
```
Comment (alancai98) [inline lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:892]: This was mostly moved from [`compileQueryWithoutProjection `](https://github.com/partiql/partiql-lang-kotlin/blob/master/lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt#L1365).

**Review by therapon — APPROVED** [review]

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt [hunk 2]
```diff
@@ -928,12 +971,16 @@ internal class EvaluatingCompiler(
...
-                            val quantifiedRows = when(setQuantifier) {
+                            var quantifiedRows = when(setQuantifier) {
                                 // wrap the ExprValue to use ExprValue.equals as the equality
                                 SetQuantifier.DISTINCT -> projectedRows.filter(createUniqueExprValueFilter())
                                 SetQuantifier.ALL -> projectedRows
                             }
 
+                            if (limit != null) {
+                                quantifiedRows = quantifiedRows.take(compileLimit(limit, env))
+                            }
```
Comment (abhikuhikar) [inline lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:982]: Can it be done using `let` to avoid using `var`?

```suggestion
                            val quantifiedRows = when(setQuantifier) {
                                // wrap the ExprValue to use ExprValue.equals as the equality
                                SetQuantifier.DISTINCT -> projectedRows.filter(createUniqueExprValueFilter())
                                SetQuantifier.ALL -> projectedRows
                            }.let { rows ->
                                when (limit) {
                                    null -> rows
                                    else -> rows.take(compileLimit(limit, env))
                                }
                            }
```

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt [hunk 3]
```diff
@@ -974,13 +1021,16 @@ internal class EvaluatingCompiler(
...
+                                    var fromProductions: Sequence<FromProduction> = sourceThunks(env)
                                     val registers = createRegisterBank()
 
                                     // note: the group key can be anything here because we only ever have a single
                                     // group when aggregates are used without GROUP BY expression
                                     val syntheticGroup = Group(valueFactory.nullValue, registers)
 
+                                    if (limit != null) {
+                                        fromProductions = fromProductions.take(compileLimit(limit, env))
+                                    }
```
Comment (abhikuhikar) [inline lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:1033]: Can it be done using `let` to avoid using `var`?

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt [hunk 4]
```diff
@@ -1085,9 +1139,13 @@ internal class EvaluatingCompiler(
                         val asThunk = compileExprNode(asExpr)
                         val atThunk = compileExprNode(atExpr)
                         thunkFactory.thunkEnv(metas) { env ->
-                            val sourceValue = sourceThunks(env)
+                            var sourceValue = sourceThunks(env).asSequence()
+
+                            if (limit != null) {
+                                sourceValue = sourceValue.take(compileLimit(limit, env))
+                            }
+
```
Comment (abhikuhikar) [inline lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:1147]: Here as well.

**Review by abhikuhikar — CHANGES_REQUESTED** [review]

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 4 above)
Comment (dlurton) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:1147]: +1

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 3 above)
Comment (dlurton) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:1033]: +1

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 2 above)
Comment (dlurton) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:982]: +1

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt [hunk 5]
```diff
@@ -928,12 +971,16 @@ internal class EvaluatingCompiler(
...
 
-                            val quantifiedRows = when(setQuantifier) {
+                            var quantifiedRows = when(setQuantifier) {
                                 // wrap the ExprValue to use ExprValue.equals as the equality
                                 SetQuantifier.DISTINCT -> projectedRows.filter(createUniqueExprValueFilter())
                                 SetQuantifier.ALL -> projectedRows
                             }
 
+                            if (limit != null) {
+                                quantifiedRows = quantifiedRows.take(compileLimit(limit, env))
```
Comment (dlurton) [inline lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:981]: Since this is inside a call to `thunkFactory.thunkEnv(metas)` (line 968), the call to `compileLimit` is being invoked at *evaluation-time*, which means the limit clause is being re-compiled for every row.  To fix this move the `compileLimit` call outside of the closure, i.e. to 964.

Comment (dlurton) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:981]: This is an important aspect of how `EvaluatingCompiler` works: a significant portion of the the code in it  executes at evaluation-time and not-compile time because it resides in closures (thunks) such as this one.  It is important to avoid re-compiling parts of expressions within the body of a thunk.

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt [hunk 6]
```diff
@@ -974,13 +1021,16 @@ internal class EvaluatingCompiler(
...
-                                    val fromProductions: Sequence<FromProduction> = sourceThunks(env)
+                                    var fromProductions: Sequence<FromProduction> = sourceThunks(env)
                                     val registers = createRegisterBank()
 
                                     // note: the group key can be anything here because we only ever have a single
                                     // group when aggregates are used without GROUP BY expression
                                     val syntheticGroup = Group(valueFactory.nullValue, registers)
 
+                                    if (limit != null) {
+                                        fromProductions = fromProductions.take(compileLimit(limit, env))
```
Comment (dlurton) [inline lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:1032]: Move `compileLimit` outside of thunk body.

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 1 above)
Comment (dlurton) [inline lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:892]: In general, any `compile*` function should return a thunk.  This appears to be compiling and evaluating.  Compilation and evaluation should be separate steps.

**Review by dlurton — CHANGES_REQUESTED** [review]
Need to avoid re-compiling the LIMIT clause by moving it's thunk creations outside of the body of all of its thunks.

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 2 above)
Comment (alancai98) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:983]: Thanks, updated w/ the suggestion.

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 4 above)
Comment (alancai98) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt]: Updated

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 3 above)
Comment (alancai98) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt]: Updated

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 5 above)
Comment (alancai98) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt]: I separated out the compilation ([L955](https://github.com/partiql/partiql-lang-kotlin/blob/ad2aa3e73f549c3ff66605d254c2c5b7dfdbc277/lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt#L955)) from the evaluation ([L892](https://github.com/partiql/partiql-lang-kotlin/blob/ad2aa3e73f549c3ff66605d254c2c5b7dfdbc277/lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt#L892)) so the compilation isn't done for every row.

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 6 above)
Comment (alancai98) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt]: In the new commit, I separated out the compilation ([L955](https://github.com/partiql/partiql-lang-kotlin/blob/ad2aa3e73f549c3ff66605d254c2c5b7dfdbc277/lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt#L955)) from the evaluation ([L892](https://github.com/partiql/partiql-lang-kotlin/blob/ad2aa3e73f549c3ff66605d254c2c5b7dfdbc277/lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt#L892)) so the compilation isn't done from within the thunk evaluation.

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 1 above)
Comment (alancai98) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt]: In the new commit, I separated out the compilation ([L955](https://github.com/partiql/partiql-lang-kotlin/blob/ad2aa3e73f549c3ff66605d254c2c5b7dfdbc277/lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt#L955)) from the evaluation ([L892](https://github.com/partiql/partiql-lang-kotlin/blob/ad2aa3e73f549c3ff66605d254c2c5b7dfdbc277/lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt#L892)).

**Review by abhikuhikar — DISMISSED** [review]

**Review by therapon — DISMISSED** [review]

**Review by therapon — APPROVED** [review]

**Review by therapon — APPROVED** [review]

**Review by dlurton — APPROVED** [review]
