### PR TITLE
Fix to aggregate being used in subquery binding error

### LINKED ISSUE #212: Unexpected "no such binding" errors when aggregate used in subquery of SELECT VALUE from source
The following error doesn't make any sense to me whatsoever since `foo` is the alias being given to the result of the nested query.

```
partiql> select value foo.cnt from (select count(*) as cnt from [1, 2, 3]) as foo
   | 
software.amazon.sql.eval.EvaluationException: No such binding: foo
        Evaluator Error: at line 1, column 14: Binding does not exist, <UNKNOWN> : <UNKNOWN>

        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileVariableReference$$inlined$thunkEnv$1.invoke(Thunk.kt:237)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileVariableReference$$inlined$thunkEnv$1.invoke(Thunk.kt)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compilePath$$inlined$thunkEnv$1.invoke(Thunk.kt:237)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compilePath$$inlined$thunkEnv$1.invoke(Thunk.kt)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileSelect$1$$special$$inlined$thunkEnvValue$1.invoke(Thunk.kt:237)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileSelect$1$$special$$inlined$thunkEnvValue$1.invoke(Thunk.kt)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileSelect$1$1$getQueryThunk$$inlined$thunkEnv$2.invoke(Thunk.kt:258)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileSelect$1$1$getQueryThunk$$inlined$thunkEnv$2.invoke(Thunk.kt)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileSelect$1$1$getQueryThunk$$inlined$thunkEnv$4.invoke(Thunk.kt:237)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileSelect$1$1$getQueryThunk$$inlined$thunkEnv$4.invoke(Thunk.kt)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compile$1.eval(EvaluatingCompiler.kt:205)
        at software.amazon.sqlcli.Repl$run$totalMs$1.invoke(Repl.kt:92)
        at software.amazon.sqlcli.Repl$run$totalMs$1.invoke(Repl.kt:35)
        at software.amazon.sqlcli.StopwatchKt.timeIt(stopwatch.kt:21)
        at software.amazon.sqlcli.Repl.run(Repl.kt:70)
        at software.amazon.sqlcli.Main.runRepl(main.kt:158)
        at software.amazon.sqlcli.Main.main(main.kt:143)

ERROR! (5 ms)
```

The result I expect is: `<< 3 >>`

This also seems wrong--in this case, `baz` is the alias assigned to the single from source within the nested query.

```
partiql> select value foo.cnt from (select count(baz.bar) as cnt from [ { 'bar': 1 }, { 'bar': 2}] as baz) as foo
   | 
software.amazon.sql.eval.EvaluationException: No such binding: baz
        Evaluator Error: at line 1, column 41: Binding does not exist, <UNKNOWN> : <UNKNOWN>

        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileVariableReference$$inlined$thunkEnv$1.invoke(Thunk.kt:237)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileVariableReference$$inlined$thunkEnv$1.invoke(Thunk.kt)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compilePath$$inlined$thunkEnv$1.invoke(Thunk.kt:237)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compilePath$$inlined$thunkEnv$1.invoke(Thunk.kt)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileSelect$1$1$getQueryThunk$$inlined$thunkEnv$2.invoke(Thunk.kt:251)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileSelect$1$1$getQueryThunk$$inlined$thunkEnv$2.invoke(Thunk.kt)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileSelect$1$1$getQueryThunk$$inlined$thunkEnv$4.invoke(Thunk.kt:237)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compileSelect$1$1$getQueryThunk$$inlined$thunkEnv$4.invoke(Thunk.kt)
        at software.amazon.sql.impl.eval.EvaluatingCompiler$compile$1.eval(EvaluatingCompiler.kt:205)
        at software.amazon.sqlcli.Repl$run$totalMs$1.invoke(Repl.kt:92)
        at software.amazon.sqlcli.Repl$run$totalMs$1.invoke(Repl.kt:35)
        at software.amazon.sqlcli.StopwatchKt.timeIt(stopwatch.kt:21)
        at software.amazon.sqlcli.Repl.run(Repl.kt:70)
        at software.amazon.sqlcli.Main.runRepl(main.kt:158)
        at software.amazon.sqlcli.Main.main(main.kt:143)

ERROR! (5 ms)
```

Changing `count(baz.bar) as cnt` to simply `baz.bar as cnt` yields the following (which is the expected result), so probably this has something to do with aggregate support.

```
partiql> select value foo.cnt from (select baz.bar as cnt from [ { 'bar': 1 }, { 'bar': 2}] as baz) as foo
   | 
===' 
1
2
--- 
Result type was BAG and contained 2 items
OK! (6 ms)
```

### PR DESCRIPTION
**Pull request by alancai98**
Fixes #212.

The cause appears to be from the `AggregateSupport(Rewriter/VisitorTransform)`, which at a high level, populates a meta containing information about the query's aggregation functions. 

It was not correctly excluding subqueries when creating a list of aggregates. So in a query with aggregates in a subquery such as `SELECT 1 FROM (SELECT COUNT(1) FROM foo)`, the outer `SELECT`'s metas would contain the subquery's aggregate metas. Because of this, the wrong evaluation path was taken in the `EvaluatingCompiler`:https://github.com/partiql/partiql-lang-kotlin/blob/de1fe32b1d535a9d56b3337b1de9c10780422745/lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt#L972

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: lang/test/org/partiql/lang/eval/EvaluatingCompilerTests.kt [hunk 1]
```diff
@@ -1771,4 +1771,40 @@ class EvaluatingCompilerTests : EvaluatorTestBase() {
...
+    fun aggregateWithAliasingInSubqueryOfSelectValue() =
+        assertEvalExprValue(
+            """
+            SELECT VALUE foo.cnt
+            FROM
+                (SELECT COUNT(baz.bar) AS cnt 
+                FROM << { 'bar': 1 }, { 'bar': 2 } >> AS baz)
+            AS foo
+            """,
+            "<< 2 >>")
```
Comment (alancai98) [inline lang/test/org/partiql/lang/eval/EvaluatingCompilerTests.kt:1809]: Test cases taken from #212.

File: lang/src/org/partiql/lang/eval/visitors/AggregateSupportVisitorTransform.kt [hunk 2]
```diff
@@ -18,73 +18,46 @@ import com.amazon.ionelement.api.MetaContainer
...
+
+    override fun transformExprCallAgg(node: PartiqlAst.Expr.CallAgg): PartiqlAst.Expr {
+        val transformedCallAgg = PartiqlAst.build {
+            callAgg_(
+                setq = node.setq,
+                funcName = node.funcName,
+                arg = transformExpr(node.arg),
+                metas = transformMetas(node.metas) + metaContainerOf(AggregateRegisterIdMeta.TAG to AggregateRegisterIdMeta(aggregateCallSites.size)))
         }
+        aggregateCallSites.add(transformedCallAgg)
```
Comment (alancai98) [inline lang/src/org/partiql/lang/eval/visitors/AggregateSupportVisitorTransform.kt:50]: This rearrangement of the two lines has no impact on the actual logic other than adding the `AggregateRegisterIdMeta` to each `aggregateCallSites`' metas, which will be in the `SELECT` clause's `AggregateCallSiteListMeta` meta.

This made it significantly more clean to test the `AggregateRegisterIdMeta` for the right value in testing.

File: lang/test/org/partiql/lang/eval/visitors/AggregateSupportVisitorTransformTests.kt [hunk 3]
```diff
@@ -0,0 +1,286 @@
...
+
+        val actualMetas = select.metas
+        val expectedMetas = createCallAggMetas(listOf(Pair("count", 0)))
+
+        assertSameCallAggMetas(expectedMetas, actualMetas)
+    }
+
+    @Test
+    fun `one aggregate in HAVING transform`() {
+        val query = "SELECT 1 FROM foo GROUP BY bar HAVING SUM(1) > 0"
```
Comment (dlurton) [inline lang/test/org/partiql/lang/eval/visitors/AggregateSupportVisitorTransformTests.kt:93]: I think there's an opportunity to parameterize these tests here since at least the first several seem nearly identical.

**Review by dlurton — CHANGES_REQUESTED** [review]
Mostly LGTM, I think we just need to parameterize and/or factor the tests to be less repetitive.

File: lang/test/org/partiql/lang/eval/visitors/AggregateSupportVisitorTransformTests.kt (hunk 3 above)
Comment (alancai98) [reply lang/test/org/partiql/lang/eval/visitors/AggregateSupportVisitorTransformTests.kt]: I parameterized the non-subquery tests in the latest commit. At the moment can't think of a clean way to parameterize tests (or remove some repetition) with subqueries.

**Review by dlurton — APPROVED** [review]
