### PR TITLE
Error code for / and % by zero

### LINKED ISSUE #198: Handle % by zero errors
They should have proper error codes like divide by zero has
```
ionsql> 1 % 0
      |
com.amazon.ionsql.eval.EvaluationException: Internal error, / by zero
	<UNKNOWN>: at line 1, column 3: <UNKNOWN>

	at com.amazon.ionsql.eval.RuntimeExprThunk.eval(EvaluatingCompiler.kt:51)
	at com.amazon.ionsql.eval.EvaluatingCompiler$compile$2.eval(EvaluatingCompiler.kt:1548)
	at com.amazon.ionsql.eval.EvaluatingCompiler.eval(EvaluatingCompiler.kt:1527)
	at com.amazon.ionsql.eval.EvaluatingCompiler$compile$3.eval(EvaluatingCompiler.kt:1560)
	at com.amazon.ionsql.tools.REPL.main(REPL.kt:186)
Caused by: java.lang.ArithmeticException: / by zero
	at com.amazon.ionsql.util.NumberExtensionsKt.rem(NumberExtensions.kt:199)
	at com.amazon.ionsql.eval.EvaluatingCompiler$syntaxTable$16.invoke(EvaluatingCompiler.kt:456)
	at com.amazon.ionsql.eval.EvaluatingCompiler$syntaxTable$16.invoke(EvaluatingCompiler.kt:101)
	at com.amazon.ionsql.eval.ExprFunction$Companion$over$1.call(ExprFunction.kt:19)
	at com.amazon.ionsql.eval.EvaluatingCompiler$compileFunc$2.invoke(EvaluatingCompiler.kt:1472)
	at com.amazon.ionsql.eval.EvaluatingCompiler$compileFunc$2.invoke(EvaluatingCompiler.kt:101)
	at com.amazon.ionsql.eval.EvaluatingCompiler$exprThunk$1.innerEval(EvaluatingCompiler.kt:120)
	at com.amazon.ionsql.eval.RuntimeExprThunk.eval(EvaluatingCompiler.kt:33)
	... 4 more

ERROR! (49 ms)
ionsql> 1 / 0
      |
com.amazon.ionsql.eval.EvaluationException: / by zero
	<UNKNOWN>: at line 1, column 3: <UNKNOWN>

	at com.amazon.ionsql.eval.RuntimeExprThunk.eval(EvaluatingCompiler.kt:37)
	at com.amazon.ionsql.eval.EvaluatingCompiler$compile$2.eval(EvaluatingCompiler.kt:1548)
	at com.amazon.ionsql.eval.EvaluatingCompiler.eval(EvaluatingCompiler.kt:1527)
	at com.amazon.ionsql.eval.EvaluatingCompiler$compile$3.eval(EvaluatingCompiler.kt:1560)
	at com.amazon.ionsql.tools.REPL.main(REPL.kt:186)
Caused by: com.amazon.ionsql.eval.EvaluationException: / by zero
	<UNKNOWN>: at line <UNKNOWN>, column <UNKNOWN>: <UNKNOWN>

	at com.amazon.ionsql.eval.ExceptionsKt.err(Exceptions.kt:44)
	at com.amazon.ionsql.eval.ExceptionsKt.errNoContext(Exceptions.kt:40)
	at com.amazon.ionsql.eval.EvaluatingCompiler$syntaxTable$15.invoke(EvaluatingCompiler.kt:448)
	at com.amazon.ionsql.eval.EvaluatingCompiler$syntaxTable$15.invoke(EvaluatingCompiler.kt:101)
	at com.amazon.ionsql.eval.ExprFunction$Companion$over$1.call(ExprFunction.kt:19)
	at com.amazon.ionsql.eval.EvaluatingCompiler$compileFunc$2.invoke(EvaluatingCompiler.kt:1472)
	at com.amazon.ionsql.eval.EvaluatingCompiler$compileFunc$2.invoke(EvaluatingCompiler.kt:101)
	at com.amazon.ionsql.eval.EvaluatingCompiler$exprThunk$1.innerEval(EvaluatingCompiler.kt:120)
	at com.amazon.ionsql.eval.RuntimeExprThunk.eval(EvaluatingCompiler.kt:33)
	... 4 more
```

### PR DESCRIPTION
**Pull request by raganhan**
resolves #198 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: lang/src/org/partiql/lang/errors/ErrorCode.kt [hunk 1]
```diff
@@ -552,6 +552,16 @@ enum class ErrorCode(private val category: ErrorCategory,
...
 
+    EVALUATOR_DIVIDE_BY_ZERO(
+        ErrorCategory.EVALUATOR,
+        LOCATION,
+        "/ by zero"),
+
+    EVALUATOR_MODULO_BY_ZERO(
+        ErrorCategory.EVALUATOR,
+        LOCATION,
+        "% by zero"),
```
Comment (dlurton) [inline lang/src/org/partiql/lang/errors/ErrorCode.kt]: I'm not certain there's a good reason to have a separate error code for modulo by zero.

For precedence, the JVM's error message for `1 % 0` is: `java.lang.ArithmeticException: / by zero`

Comment (raganhan) [reply lang/src/org/partiql/lang/errors/ErrorCode.kt]: I think it's worth it to have a better error message.
