### PR TITLE
Makes the PartiQLParser the default Parser

### LINKED ISSUE #760: Replace SqlParser with PartiQLParser in the Evaluator Pipeline tests
## Description
The evaluator pipeline tests use SqlParser. 

- https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/src/org/partiql/lang/planner/PlannerPipeline.kt#L412
- https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/src/org/partiql/lang/CompilerPipeline.kt#L232
- https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/test/org/partiql/lang/eval/evaluatortestframework/PartiQLCompilerPipelineFactory.kt#L74

Some source location metas are missing from the AST generated by the PartiQLParser which causes ~350 cast tests to fail

```
 org.partiql.lang.eval.evaluatortestframework.EvaluatorAssertionFailedError: Failure reason: UNEXPECTED_ERROR_CODE
    Note                           : PartiQLCompilerPipeline (Typing mode forced to LEGACY)
    Group name                     : null
    Query                          : CAST('<< 1 >>' AS RS_FLOAT)
    Target pipeline                : ALL_PIPELINES
    Expected error code            : EVALUATOR_CAST_FAILED
    Actual error code              : EVALUATOR_CAST_FAILED_NO_LOCATION
    Expected error context         : null
    Expected internal flag         : null
    Expected permissive mode result: MISSING
``` 

## Expected Behavior
All tests should pass

## Additional Context
Consider doing https://github.com/partiql/partiql-lang-kotlin/issues/758 first

### PR DESCRIPTION
**Pull request by johnedquinn**
## Relevant Issues
- Closes #760 

## Description
- Makes the PartiQLParser the default Parser for the Compiler Pipeline, etc
- Makes changes to pass all tests, including:
  - Making unary minus/plus act directly on numeric literals
  - Adds metas to several AST nodes
- Updates examples directory
- No backwards incompatible changes
- Has not yet updated CHANGELOG
- No external dependencies added

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: lang/test/org/partiql/lang/eval/evaluatortestframework/PartiQLCompilerPipelineFactory.kt [hunk 1]
```diff
@@ -71,7 +71,7 @@ internal class PartiQLCompilerPipelineFactory : PipelineFactory {
         )
 
         val pipeline = PartiQLCompilerPipeline(
-            parser = SqlParser(ION, legacyPipeline.customDataTypes),
+            parser = PartiQLParserBuilder().ionSystem(ION).customTypes(legacyPipeline.customDataTypes).build(),
             planner = PartiQLPlannerBuilder.standard()
                 .options(plannerOptions)
                 .globalVariableResolver(globalVariableResolver)
```
Comment (RCHowell) [inline lang/test/org/partiql/lang/eval/evaluatortestframework/PartiQLCompilerPipelineFactory.kt:77]: nit: we can replace this with `PartiQLCompilerPipeline.build { ... }` now, don't block the PR on this though

**Review by RCHowell — APPROVED** [review]
