### PR TITLE
Fix `INTERVAL` precision containing a range of fields

### LINKED ISSUE #1820: `INTERVAL` doesn't support precision exceeding 6 with a range of fields
## Description
- The maximum allowing precision for `INTERVAL` should be 9. However, it will throw an error when the interval contains a range of fields.

### Current Behavior
```
partiql ▶ INTERVAL '99:59.123456789' MINUTE(2) TO SECOND(9);
e: [syntax] Unexpected failure encountered. Caused by: java.lang.IllegalArgumentException: Invalid end field precision9.
java.lang.IllegalArgumentException: Invalid end field precision9 

partiql ▶ INTERVAL '999999999-11' YEAR(9) to MONTH;
e: [syntax] Unexpected failure encountered. Caused by: java.lang.IllegalArgumentException: Invalid leading field precision 9.
java.lang.IllegalArgumentException: Invalid leading field precision 9 
```

## Additional Context
- PartiQL version: 1.2.2

### PR DESCRIPTION
**Pull request by XuechunHHH**
## Relevant Issues
- Closes #1820 

## Description
- Set the maximum precision as 9 for PartiQL `INTERVAL` in the AST

### Current Behavior
```
partiql ▶ INTERVAL '999999999-11' YEAR(9) to MONTH;

=== RESULT ===
INTERVAL '999999999-11' YEAR (9) TO MONTH

OK!

partiql ▶ INTERVAL '99:59.123456789' MINUTE(2) TO SECOND(9);

=== RESULT ===
INTERVAL '99:59.123456789' MINUTE (2) TO SECOND (9)

OK!
```

## Other Information
- Updated Unreleased Section in CHANGELOG: **[NO]**
- Any backward-incompatible changes? **[NO]**
- Any new external dependencies? **[NO]**
- Do your changes comply with the [contributing][cg] and [code style][csg] guidelines? **[YES]**

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

[cg]: https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md
[csg]: https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md

### CODE REVIEW

**Review by alancai98 — APPROVED** [review]

File: partiql-ast/src/main/java/org/partiql/ast/IntervalQualifier.java [hunk 1]
```diff
@@ -16,8 +16,8 @@
  */
 public abstract class IntervalQualifier extends AstNode {
 
-    // TODO: Determine what the maximum precision is for PartiQL
-    private static final int MAX_PRECISION = 6;
+    // The maximum precision is 9 for PartiQL INTERVAL
+    private static final int MAX_PRECISION = 9;
```
Comment (xd1313113) [inline partiql-ast/src/main/java/org/partiql/ast/IntervalQualifier.java:20]: Is this being used after Alan's refactor? I think we are using 
    `internal const val INTERVAL_MAX_PRECISION = 9
    private const val INTERVAL_DEFAULT_FRACTIONAL_PRECISION = 6`
from https://github.com/partiql/partiql-lang-kotlin/blob/main/partiql-spi/src/main/kotlin/org/partiql/spi/utils/IntervalUtils.kt#L14-L15

Comment (XuechunHHH) [reply partiql-ast/src/main/java/org/partiql/ast/IntervalQualifier.java:20]: Yes. We decided to set `MAX_PRECISION = 9` for `INTERVAL`. This code change is for `partiql-ast`.
